// <auto-generated />
using System;
using Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdminUI.Migrations
{
    [DbContext(typeof(SubmissionContext))]
    [Migration("20200603190137_Remove_Submission_Index_Generation")]
    partial class Remove_Submission_Index_Generation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Common.Models.Lock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lock");
                });

            modelBuilder.Entity("Common.Models.MileageEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Group")
                        .HasColumnType("bit");

                    b.Property<int?>("MileageFormId")
                        .HasColumnType("int");

                    b.Property<double>("Miles")
                        .HasColumnType("float");

                    b.Property<string>("PurposeOfTrip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MileageFormId");

                    b.ToTable("MileageEntry");
                });

            modelBuilder.Entity("Common.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientPrime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Edited")
                        .HasColumnType("bit");

                    b.Property<string>("FormType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LockInfoId")
                        .HasColumnType("int");

                    b.Property<string>("ProgressNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceGoal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Submitted")
                        .HasColumnType("datetime2");

                    b.Property<string>("UriString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserActivity")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LockInfoId");

                    b.ToTable("Submissions");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Submission");
                });

            modelBuilder.Entity("Common.Models.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Group")
                        .HasColumnType("bit");

                    b.Property<double>("Hours")
                        .HasColumnType("float");

                    b.Property<DateTime>("In")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Out")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimesheetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimesheetId");

                    b.ToTable("TimeEntry");
                });

            modelBuilder.Entity("Common.Models.MileageForm", b =>
                {
                    b.HasBaseType("Common.Models.Submission");

                    b.Property<double>("TotalMiles")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("MileageForm");
                });

            modelBuilder.Entity("Common.Models.Timesheet", b =>
                {
                    b.HasBaseType("Common.Models.Submission");

                    b.Property<double>("TotalHours")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Timesheet");
                });

            modelBuilder.Entity("Common.Models.MileageEntry", b =>
                {
                    b.HasOne("Common.Models.MileageForm", null)
                        .WithMany("MileageEntries")
                        .HasForeignKey("MileageFormId");
                });

            modelBuilder.Entity("Common.Models.Submission", b =>
                {
                    b.HasOne("Common.Models.Lock", "LockInfo")
                        .WithMany()
                        .HasForeignKey("LockInfoId");
                });

            modelBuilder.Entity("Common.Models.TimeEntry", b =>
                {
                    b.HasOne("Common.Models.Timesheet", null)
                        .WithMany("TimeEntries")
                        .HasForeignKey("TimesheetId");
                });
#pragma warning restore 612, 618
        }
    }
}
